import { languages } from '@/i18n/settings'
import { ReduxStoreProvider } from '@/providers/redux-store-provider'
import { ChildProps } from '@/types/types'
import { ClerkProvider } from '@clerk/nextjs'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { dir } from 'i18next'
import type { Metadata } from 'next'
import { Space_Grotesk as SpaceGrotesk } from 'next/font/google'
import { Toaster } from 'sonner'
import { extractRouterConfig } from 'uploadthing/server'
import { ourFileRouter } from './api/uploadthing/core'
import './globals.css'
// import { store } from '@store/index'

const spaceGrotesk = SpaceGrotesk({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-space-grotesk',
})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
interface RootProps extends ChildProps {
	params: { lng: string }
}
// faqatgina biz bergan tillarni qabul qilishu uchun
export async function generateStaticParams() {
	return languages.map(lng => ({ lng }))
}

export default function RootLayout({ children, params: { lng } }: RootProps) {
	return (
		<ClerkProvider>
			<html lang={lng} dir={dir(lng)}>
				<body
					className={` ${spaceGrotesk.variable}  overflow-x-hidden custom-scrollbar`}
				>
					<NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
					<ReduxStoreProvider>{children}</ReduxStoreProvider>
					<Toaster position='top-center' />
				</body>
			</html>
		</ClerkProvider>
	)
}
